# Generated by Django 4.2.7 on 2023-11-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rate",
            name="rate",
        ),
        migrations.AddField(
            model_name="rate",
            name="buy",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rate",
            name="sell",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rate",
            name="vendor",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
