name: pytest

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        run: |
          pip install --quiet -r requirements.txt
          pytest