name: pytest

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        name: Install dependencies, run tests
        run:
          pip install -r requirements.txt
          pytest
